{
 "title": "BIOMERO Log Analysis",
 "tags": [
  "biomero",
  "logs",
  "main"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "manual_uuid" },
   { "name": "log_level", "query": "ERROR,WARN,INFO,DEBUG" },
   { "name": "thread", "query": ".*" }
  ]
 },
 "panels": [
  {
   "title": "Log Level logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"biomero\"} |= \"${log_level}\""
    }
   ]
  },
  {
   "title": "Workflow tracking",
   "type": "logs",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{job=\"biomero\", service=\"biomeroworker\", filename=\"/logs/biomeroworker/biomero.log\"} |= `${manual_uuid}` |~ `\\[${thread}\\]`"
    }
   ]
  },
  {
   "title": "All BIOMERO logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{job=\"biomero\"}"
    }
   ]
  }
 ]
}